# Generated by Django 3.1.7 on 2021-04-06 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yt_id', models.CharField(max_length=32, unique=True)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('published_at', models.DateTimeField()),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['yt_id'], name='video_video_yt_id_1a2d72_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['published_at'], name='video_video_publish_fcae89_idx'),
        ),
    ]
